### ISSUE TITLE
How should "Sign now" link work?

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/giraffe#129]
If I load https://broom.moveon.org/2018r/sign/georgia-add-outkast-to and start filling out the form, it's possible to fill out the entire form and only see the "Sign now" button and not the "Submit" button, e.g.:

<img width="1322" alt="screen shot 2018-03-27 at 9 20 25 am" src="https://user-images.githubusercontent.com/108645/37977141-69414e14-31a0-11e8-890f-35ed544bafe6.png">

That looks like clicking "Sign now" would submit the form, but what it actually does is put focus on the form, which is confusing when I've already filled out the form.

Not sure what exactly we should change here. E.g. should the link's behavior change when the form is already filled out? Should it always submit the form and just do the normal validation prompt when the form is still empty? Should the link not even be there in this context?

**Comment by sreynen** [comment]
@hi0ctane I just learned the original idea of this button was that it would show on desktop, but only when the form has been scrolled off the page. Thoughts on that vs. removing it from desktop entirely?

**Comment by jparkrr** [comment]
I implemented something that hides the button when the form is visible on both mobile and desktop. I figured it doesn't hurt to keep it on desktop since it wasn't more work, but I can remove it  there if you want.

Potentially "sign now" makes sense now that it's not visible at the same time as the form, but let me know.

**Comment by jparkrr** [comment]
This is working on staging now https://broom.moveon.org/2018r/sign/keep-hearst-elementary?source=petitionshomepage
