### ISSUE TITLE
Survey Question label font color inconsistent 

### ISSUE THREAD

**Issue by KatieW1001** [MoveOnOrg/giraffe#145]
https://act.moveon.org/survey/VA2017field_nondelegatevolunteer_copyswarm/?template_set=main-giraffe
"How many hours can you commit to volunteering between now and Election Day, November 7, 2017? (Select one.)" appears to be a slightly darker shade of grey than "When can you volunteer? (Anytime, weekends, weekday evenings, etc.)"

**Comment by mstephani** [comment]
Created this PR for the fix: https://github.com/MoveOnOrg/giraffe/pull/158
