### ISSUE TITLE
checkbox styling: make checkboxes bigger and add padding

### ISSUE THREAD

**Issue by mathemagica** [MoveOnOrg/giraffe#162]
Please make .checkbox-input 25x25px instead of 20x20px, and add 5px of padding to .checkbox-item

This'll improve the usability of checkbox items in surveys.

currently:
![image](https://user-images.githubusercontent.com/2147383/38276753-118e2a2e-3764-11e8-911c-1bcb66344ccb.png)
![image](https://user-images.githubusercontent.com/2147383/38276805-3a4ecf72-3764-11e8-9eb3-e9e041ac3b29.png)

desired:
![image](https://user-images.githubusercontent.com/2147383/38276814-41b07626-3764-11e8-8cf0-5142e765eb35.png)
![image](https://user-images.githubusercontent.com/2147383/38276820-45c3f58a-3764-11e8-892a-36b0477829da.png)

**Comment by mstephani** [comment]
Hi @mathemagica ,

Just to be 100% sure, the checkboxes should be bigger only on survey questions, right?

**Comment by mathemagica** [comment]
Yes, only on survey questions. Thx for checking

**Comment by mstephani** [comment]
Hi @mathemagica ,

Here is PR: https://github.com/MoveOnOrg/ak-template-set/pull/509
