### ISSUE TITLE
small loading svg?

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/giraffe#187]
https://github.com/MoveOnOrg/giraffe/issues/74
is a good image that's currently 4.3Kb.  I wonder if we could make this an svg that's inlineable and measured in bytes.

If you send a non-optimized svg, I can try to optimize it and keep the dimensions, etc.

**Comment by jparkrr** [comment]
might be hard to have an animated svg, but I'm not sure

**Comment by schuyler1d** [comment]
yeah, this might be too hard
