### ISSUE TITLE
Optimize font loads

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/giraffe#189]
We currently have the fonts below defined in the css, however it looks like we never use:
* `Roboto Condensed` (non bold)
* `Roboto Medium`
* `Roboto Bold`
however these fonts are prompted for download.  If these are used somewhere, then we should at least document which sites/pages they are used on.

```
@font-face {
    font-family: 'Roboto Condensed';
    src: url(../fonts/RobotoCondensed-Regular.ttf)
}

@font-face {
    font-family: 'Roboto Condensed Bold';
    src: url(../fonts/RobotoCondensed-Bold.ttf);
    font-weight: bolder
}

@font-face {
    font-family: 'Roboto Regular';
    src: url(../fonts/Roboto-Regular.ttf)
}

@font-face {
    font-family: 'Roboto Medium';
    src: url(../fonts/Roboto-Medium.ttf)
}

@font-face {
    font-family: 'Roboto Bold';
    src: url(../fonts/Roboto-Bold.ttf)
}
```

**Comment by schuyler1d** [comment]
@hi0ctane can you confirm we aren't using those fonts anywhere?

**Comment by sandramchung** [comment]
Grepping for `roboto-bold` and `roboto-medium` (the mixin names) reveals that both are used in lots of places. Roboto Condensed is not used at all, so we can safely nix it.

With Roboto Condensed Bold and Roboto Regular, we're loading four variants of one font family. That's not crazy. Though I prefer to use CSS when possible: https://css-tricks.com/one-file-many-options-using-variable-fonts-web/

**Comment by schuyler1d** [comment]
ah was grepping for the font rather than the alias.
I'm closing since it looks like only fonts that are used are downloaded.

**Comment by sandramchung** [comment]
But we should ditch Roboto Condensed!
