### ISSUE TITLE
windows phone eats logo in header (actionkit)

### ISSUE THREAD

**Issue by codygordon** [MoveOnOrg/giraffe#198]
This was a Nokia Lumia 930.

<img width="390" alt="screen shot 2018-03-26 at 5 25 33 pm" src="https://user-images.githubusercontent.com/7341290/37939959-c423ae98-311a-11e8-96aa-280f73cf75f2.png">

**Comment by jparkrr** [comment]
This is the same thing that I was seeing in the footer in ie11, and could be fixed by this commit, which I had to temporarily revert https://github.com/MoveOnOrg/giraffe/commit/6798215fa5c13540757c30085a1b8f9cde28c2af
