### ISSUE TITLE
Font sources not compatible with IE

### ISSUE THREAD

**Issue by jalefkowit** [MoveOnOrg/giraffe#207]
I've been digging into the question of why the Giraffe webfonts don't seem to work reliably on IE (specifically IE11). 

I've noticed a consistent error message in the IE console when using these fonts, to wit: `CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.` I believe this error is pointing to the reason the fonts don't work there.

Giraffe's bundles the Roboto font family, with individual faces bundled in as TrueType (.ttf) font files. It turns out that TrueType files include a bit of metadata, one bit of which is a flag indicating whether the font is "embeddable" or not. Unlike most browsers, [IE interprets this flag as indicating whether or not the font has been licensed for webfont use](https://stackoverflow.com/a/15744240/1513260) and refuses to load the font unless the flag is both present and set to indicate that embedding is allowed.  If the flag is not set properly or is omitted, IE will refuse to load the font.

My hypothesis is that the TrueType sources currently bundled with Giraffe are either missing this flag or have it set incorrectly, leading to the IE compatibility problem. To test it, I took the bundled TTF files and ran them through an online tool that forces the "embeddable" flag to the value suitable for webfont use. After rebuilding my local Giraffe and setting my local instance of the WP site to use it instead of the Giraffe hosted as S3, the fonts started loading there without problems.

This is not a production-ready fix, as there are legal/licensing implications to taking a font file that's not set to allow embedding and forcing it to be embeddable. Google's licensing approach for Roboto is pretty permissive, so I'm going to look for an official set of Roboto sources distributed by them that's explicitly licensed for webfont use and see if building from those solves the problem.

**Comment by sandramchung** [comment]
Resolved this issue with google fonts, but if we go back to self-hosting it'll rear its ugly head again
