### ISSUE TITLE
User able to play two videos in home page carousel simultaneously

### ISSUE THREAD

**Issue by jalefkowit** [MoveOnOrg/giraffe#223]
Originally reported as [this bug in front-wordpress.](https://github.com/MoveOnOrg/front-wordpress/issues/102) The behavior of the home-hero component is really a Giraffe issue, so I'm opening this bug to file PRs against.

**Comment by jalefkowit** [comment]
So this turns out to be a knotty problem to fix. 

What we want to do is theoretically simple. We want to watch for the event of the Flickity carousel changing slides, and reach in and pause/stop any embedded videos that happen to be playing when that happens. This could be done either naïvely by iterating over all embedded players and stopping them all, or more surgically by only modifying the player in the slide that happens to be passing out of focus.

Things get complicated when we move from theory to implementation, though. [Google provides an API for working with embedded YouTube videos.](https://developers.google.com/youtube/iframe_api_reference#Getting_Started) Unfortunately, it maps poorly to what we want to do in this case. Here's a 20,000-foot summary of how you interact with it:

1. You inject a remote JavaScript file provided by YT into your document to provide an API for accessing and controlling embedded players
2. Because you don't know how long this remote file will take to load, you create a magic JavaScript function (`onYouTubeIframeAPIReady()`) that will be invoked by the YT API when it's fully bootstrapped
3. You pass this API the ID of the `iframe` element that contains the player you want to work with, and callback functions you want to have run when that player fires various events (playback starts, playback ends, etc.)
4. You write code in those callbacks to do whatever you want to do when the event associated with that callback fires.

The first complicating factor is in step 4: this API is all set up with the expectation that the events you care about are all events happening _inside the YouTube player_, while in this case the event we care about is actually a _Flickity event_ (e.g. the carousel changing slides). So you can trap Flickity's `ready` event and load the remote JS file to get the API there, but you can't put logic to control the players into Flickity's `change` event, that logic has to go into callbacks tied to YT player events. If there's a way to just take an object returned by the YT API and run commands against it imperatively outside the context of a YouTube player event, I haven't found it.

The second complicating factor is that the way you feed the `iframe` containing the player to the YT API to turn it into an object you can work with is by passing the ID of the `iframe`, and YouTube embed codes don't come with an ID on them. It's possible to filter the oEmbed logic that we've set up to take a YouTube URL and get back an embed code for it so that embed code gets an ID added to it, but that's an extra step you have to take on your own.

The _third_ complicating factor is that, while Flickity has a `change` event you can use to do stuff when the active slide in the carousel changes, it only knows the slide you're going to end up on after the transition between slides, not the previous one. You can't just take the index of the current slide and subtract one to get the index of the previous slide either, since this carousel is set to wrap around at the end and will thus roll back around to a slide with index 0 after the last one. You could get the total length of the array of slides and manually reset the index you're working with back to 0 at the appropriate moment, but now you're writing extra code just to keep yourself in sync with Flickity.

All of which made me think that this may be a bigger project than you want to take on for what is ultimately an edge case, so I wanted to flag the complications here so you could make that decision before I pour too much time into it. Thoughts?

**Comment by sandramchung** [comment]
This is a silly amount of work for a fairly harmless edge case. Let's skip it.
