### ISSUE TITLE
MOVEON: Header Section/Images appears to extend beyond intended page width

### ISSUE THREAD

**Issue by Dayologic** [MoveOnOrg/giraffe#236]
Description: Images in the header carousel appear to extend beyond the intended width of the page.
 
ENV: STG
Browser: Chrome (latest)
OS: MacOS 10.12.5
Priority: HIGH

Steps To Reproduce:

1) Navigate to: front.moveon.org
2) Examine Images in the Header Carousel 

Expected Result: The images are properly aligned with no visual discrepancies noted

Actual Result: The images appear to be partially attached to the subsequent image in the carousel.

Screenshot 1:
<img width="1678" alt="headerimage" src="https://user-images.githubusercontent.com/19258160/39274416-dbfb6ba8-48af-11e8-980f-0e9c3a04e7d9.png">

**Comment by schuyler1d** [comment]
This should fix it:
https://github.com/MoveOnOrg/giraffe/pull/235
but we need to purge the cache @sandramchung -- how do we change the css url suffix? (maybe we can document that in the wiki)

**Comment by schuyler1d** [comment]
Believe this will do it: https://github.com/MoveOnOrg/front-wordpress/pull/144

**Comment by sandramchung** [comment]
This change is deployed. Dayo also noticed a related issue in the secondary carousel. That fix is live but I'm having trouble getting the wordpress site to load the updated giraffe css.

**Comment by sandramchung** [comment]
Finally updated giraffe CSS on front.
