### ISSUE TITLE
Multi-line unordered list bullets get lost

### ISSUE THREAD

**Issue by sreynen** [MoveOnOrg/giraffe#240]
See second list on https://act.moveon.org/survey/resistandwinleaderapplication/

Should we indent multiple lines instead of wrapping under the bullet? The style guide only has single-line list items.

**Comment by sandramchung** [comment]
Suggest combining this issue with https://github.com/MoveOnOrg/giraffe/issues/242 and maybe tweaking the way `<ul>` s look.

**Comment by hi0ctane** [comment]
@sreynen @sandramchung  for some reason the bullet style is being added using ::before

to get the look in the comp here i used these styles and removed the before content



```
.giraffe ul {
Margin-left: 10px;
}
.giraffe ul li {
display: list-item;
list-style-type: disc;
position: relative;
}

```


<img width="1120" alt="screen shot 2018-05-11 at 11 26 15 am" src="https://user-images.githubusercontent.com/5332564/39932644-b5d2a03e-550e-11e8-9512-228e62d797bc.png">
