### ISSUE TITLE
Separate out app.js into separate build components

### ISSUE THREAD

**Issue by schuyler1d** [MoveOnOrg/giraffe#72]
https://github.com/MoveOnOrg/ak-template-set/issues/405 will do donation js from ak-js.
The one nice part of keeping it around is that the comps/styleguide will still work.  However, it should be possible to load, e.g. donations js separately from anything that depends on carousel js.  Ditto for navigation -- vendor.js shouldn't be necessary to load a nav.js file, e.g.

**Comment by sandramchung** [comment]
Just belatedly realized that app.js does have a sneaky jquery dependency -- in the component init() functions. But we have jquery loading in AK and on front for other reasons anyway. Sigh.
